### PR TITLE
RestTicketClient now can use REST apikey to retrieve TGT

### PR DESCRIPTION
**Pull request by alisoncallahan**
Modified RestTicketClient to accept apikeys and added corresponding test class

### CODE REVIEW

**Comment by stevenemrick** [comment]
@alisoncallahan - thanks for adding the api key functionality!
But can you help me understand the need for the [RetrieveCodeRestTestCase.java](samples/java/src/test/java/uts/rest/samples/content/RetrieveCodeRestTestCase.java) ?  The only difference I can see is that the 'version' searched is hard-coded.

**Comment by alisoncallahan** [comment]
@stevenemrick Ah, the hardcoding of version was left in accidentally - removed that now.  [RetrieveCodeRestTestCase.java](https://github.com/alisoncallahan/uts-rest-api/blob/1db2b6b62f742618846dd2dd522e70901544a56e/samples/java/src/test/java/uts/rest/samples/content/RetrieveCodeRestTestCase.java) serves as an example for using the class RestTicketClient with an API key instead of username/password.

**Comment by stevenemrick** [comment]
ok - that makes sense.  But what if instead we just modify the existing RetrieveCodeTestCase to use the api key rather than username/pw?  I can do this if you retract the RetrieveCodeRestTestCase.  I'll just go ahead and modify all the test cases to use api key since you've taken care of the RestTicketClient.  I can just comment out the `String username = System.getProperty("username")` and `String password = System.getProperty("password");`  in each case so users are aware of this option.

**Comment by stevenemrick** [comment]
Also - I should have referenced that our discussion relates to issue #5

**Comment by alisoncallahan** [comment]
@stevenemrick Sounds good. I have removed the RetrieveCodeRestTestCase.java file.

**Pull request merged**
